import{useEffect,useMemo,useRef,useState}from'react'
import{createWorker}from'tesseract.js'
import*as pdfjs from'pdfjs-dist'
import pdfWorker from'pdfjs-dist/build/pdf.worker.min.mjs?url'
import{db}from'./db'
import{extractCandidates,initialDraft}from'./extract'
import{downloadIcs}from'./ics'
import type{Candidate,CandidateMap,EventDraft,FieldType,HistoryRecord,OcrWord}from'./types'
pdfjs.GlobalWorkerOptions.workerSrc=pdfWorker
type Screen='home'|'scan'|'review'|'history'|'manual'|'settings'
const labels:Record<FieldType,string>={title:'イベント名',date:'日付',startTime:'開始時間',endTime:'終了時間',location:'場所'}
const colors:Record<FieldType,string>={title:'#2878e3',date:'#18a566',startTime:'#e6ad00',endTime:'#db3a34',location:'#8c52c9'}
const blank:CandidateMap={title:[],date:[],startTime:[],endTime:[],location:[]},emptyDraft:EventDraft={title:'',date:'',startTime:'',endTime:'',location:'',address:'',notes:''}
async function toImage(file:File){if(file.type==='application/pdf'){const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,page=await pdf.getPage(1),base=page.getViewport({scale:1}),scale=Math.min(2,2700/Math.max(base.width,base.height)),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);await page.render({canvas,viewport}).promise;let output=canvas,rotated=false;if(canvas.height/canvas.width>2.2){output=document.createElement('canvas');output.width=canvas.height;output.height=canvas.width;const ctx=output.getContext('2d')!;ctx.translate(0,canvas.width);ctx.rotate(-Math.PI/2);ctx.drawImage(canvas,0,0);rotated=true}const blob=await new Promise<Blob>((ok,no)=>output.toBlob(b=>b?ok(b):no(Error('PDFの画像化に失敗しました')),'image/png'));return{blob,url:URL.createObjectURL(blob),name:`${file.name}（1ページ目${rotated?'・自動回転':''}）`}}return{blob:file,url:URL.createObjectURL(file),name:file.name}}
export default function App(){
 const[screen,setScreen]=useState<Screen>('home'),[source,setSource]=useState<{blob:Blob;url:string;name:string}|null>(null),[progress,setProgress]=useState(''),[pct,setPct]=useState(0),[words,setWords]=useState<OcrWord[]>([]),[candidates,setCandidates]=useState<CandidateMap>(blank),[draft,setDraft]=useState<EventDraft>(emptyDraft),[initial,setInitial]=useState<EventDraft>(emptyDraft),[selected,setSelected]=useState<{type:FieldType;candidate:Candidate}|null>(null),[history,setHistory]=useState<HistoryRecord[]>([]),[error,setError]=useState('')
 const imageRef=useRef<HTMLImageElement>(null),boxes=useMemo(()=>selected?words.filter(w=>selected.candidate.wordIds.includes(w.id)):[],[selected,words])
 useEffect(()=>()=>{if(source)URL.revokeObjectURL(source.url)},[source])
 async function choose(file?:File){if(!file)return;setError('');try{if(!file.type.startsWith('image/')&&file.type!=='application/pdf')throw Error('画像またはPDFを選択してください');if(file.size>25e6)throw Error('ファイルは25MB以下にしてください');setSource(await toImage(file));setScreen('scan')}catch(e){setError(e instanceof Error?e.message:'読み込みに失敗しました')}}
 async function analyze(){if(!source)return;setError('');setProgress('OCRを準備しています');setPct(2);try{const worker=await createWorker('jpn+eng',undefined,{logger:m=>{if(m.progress){setPct(Math.round(m.progress*100));setProgress(m.status==='recognizing text'?'文字を読み取っています':'OCRを準備しています')}}});await worker.setParameters({user_defined_dpi:'300',preserve_interword_spaces:'1'});const result=await worker.recognize(source.blob,{}, {blocks:true});await worker.terminate();let wordIndex=0,lineIndex=0;const ws:OcrWord[]=[];(result.data.blocks||[]).forEach(block=>block.paragraphs.forEach(paragraph=>paragraph.lines.forEach(line=>{const lineId=`line-${lineIndex++}`;line.words.forEach(w=>ws.push({id:`w${wordIndex++}`,lineId,text:w.text,confidence:w.confidence,box:{x:w.bbox.x0,y:w.bbox.y0,width:w.bbox.x1-w.bbox.x0,height:w.bbox.y1-w.bbox.y0},fontSize:w.bbox.y1-w.bbox.y0}))})));if(!ws.length)throw Error('文字を検出できませんでした。より鮮明な画像をお試しください。');const cs=extractCandidates(ws,imageRef.current?.naturalHeight||1000),d=initialDraft(cs);setWords(ws);setCandidates(cs);setDraft(d);setInitial(d);setSelected(cs.title[0]?{type:'title',candidate:cs.title[0]}:null);setProgress('');setScreen('review')}catch(e){setProgress('');setError(e instanceof Error?e.message:'OCR処理に失敗しました')}}
 async function save(){if(!source||!draft.title||!draft.date||!draft.startTime){setError('イベント名・日付・開始時間を確認してください');return}const corrections=Object.fromEntries(Object.keys(draft).filter(k=>draft[k as keyof EventDraft]!==initial[k as keyof EventDraft]).map(k=>[k,{from:initial[k as keyof EventDraft],to:draft[k as keyof EventDraft]}]));await db.history.add({createdAt:new Date().toISOString(),sourceName:source.name,imageBlob:source.blob,ocrWords:words,candidates,final:draft,corrections});downloadIcs(draft);setScreen('home')}
 async function openHistory(){const hs=await db.history.orderBy('createdAt').reverse().toArray();setHistory(hs.map(h=>({...h,imageUrl:URL.createObjectURL(h.imageBlob)})));setScreen('history')}
 const home=()=>{setError('');setScreen('home')}
 return<><header><button className="brand" onClick={home}><span>✓</span>Schedule Scan</button>{screen!=='home'&&<button className="link" onClick={home}>ホーム</button>}</header><main>{error&&<div className="error">{error}</div>}
 {screen==='home'&&<section className="home"><div className="hero"><p className="eyebrow">端末内で安全に読み取り</p><h1>予定を、画像から<br/>カレンダーへ。</h1><p>スクリーンショット、写真、PDFを選んでください。内容を確認してから登録できます。</p></div><div className="menu"><label className="menuItem primary"><input type="file" accept="image/*,application/pdf" onChange={e=>choose(e.target.files?.[0])}/><b>予定を読み取る</b><span>画像・PDFを選択 →</span></label><button className="menuItem" onClick={openHistory}><b>履歴を見る</b><span>保存した予定を確認 →</span></button><button className="menuItem" onClick={()=>{setDraft(emptyDraft);setScreen('manual')}}><b>手入力登録</b><span>予定を直接入力 →</span></button><button className="menuItem" onClick={()=>setScreen('settings')}><b>設定</b><span>アプリについて →</span></button></div></section>}
 {screen==='scan'&&<section className="narrow"><h1>予定を読み取る</h1><p className="muted">選択した画像を端末内で解析します。画像は外部サービスへ送信されません。</p>{source&&<div className="preview"><img ref={imageRef} src={source.url} alt="選択した資料"/><div><b>{source.name}</b><label className="link">選び直す<input type="file" accept="image/*,application/pdf" onChange={e=>choose(e.target.files?.[0])}/></label></div></div>}{progress?<div className="progress"><div><span>{progress}</span><b>{pct}%</b></div><progress value={pct} max="100"/></div>:<button className="action" onClick={analyze}>解析を開始</button>}</section>}
 {screen==='review'&&source&&<section><div className="pageTitle"><div><p className="eyebrow">解析完了</p><h1>内容を確認</h1></div><p>候補を選ぶと、読み取った箇所を画像上に表示します。</p></div><div className="review"><div className="imagePanel"><div className="imageWrap"><img ref={imageRef} src={source.url} alt="解析した資料"/>{imageRef.current&&boxes.map(w=><span key={w.id} className="box" style={{left:`${w.box.x/imageRef.current!.naturalWidth*100}%`,top:`${w.box.y/imageRef.current!.naturalHeight*100}%`,width:`${w.box.width/imageRef.current!.naturalWidth*100}%`,height:`${w.box.height/imageRef.current!.naturalHeight*100}%`,borderColor:selected?colors[selected.type]:colors.title}}/>)}</div><div className="legend">{(Object.keys(labels)as FieldType[]).map(k=><span key={k}><i style={{background:colors[k]}}/>{labels[k]}</span>)}</div></div><div className="formPanel">{(Object.keys(labels)as FieldType[]).map(type=><Field key={type} type={type} value={draft[type]} candidates={candidates[type]} selected={selected?.candidate.id} onChange={v=>setDraft({...draft,[type]:v})} onSelect={c=>{setDraft({...draft,[type]:c.value});setSelected({type,candidate:c})}}/>)}<label>住所（任意）<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>メモ（任意）<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><button className="action" onClick={save}>確認してカレンダー登録</button><p className="fine">.icsファイルを保存し、対応するカレンダーアプリで開けます。</p></div></div></section>}
 {screen==='manual'&&<section className="narrow"><h1>手入力登録</h1><div className="formPanel standalone"><SimpleForm draft={draft} setDraft={setDraft}/><button className="action" onClick={()=>draft.title&&draft.date&&draft.startTime?(downloadIcs(draft),home()):setError('イベント名・日付・開始時間を入力してください')}>カレンダー登録</button></div></section>}
 {screen==='history'&&<section><div className="pageTitle"><div><p className="eyebrow">この端末に保存</p><h1>履歴</h1></div><p>{history.length}件の予定</p></div>{!history.length?<div className="empty">まだ履歴はありません。</div>:<div className="historyGrid">{history.map(h=><article key={h.id}><img src={h.imageUrl} alt="元資料"/><div><time>{new Date(h.createdAt).toLocaleString('ja-JP')}</time><h2>{h.final.title}</h2><p>{h.final.date} {h.final.startTime}{h.final.endTime&&`–${h.final.endTime}`}</p><p>{h.final.location}</p><button className="link" onClick={()=>downloadIcs(h.final)}>もう一度登録</button></div></article>)}</div>}</section>}
 {screen==='settings'&&<section className="narrow"><h1>設定</h1><div className="info"><h2>プライバシー</h2><p>OCR処理と予定情報の抽出はブラウザ内で行います。元画像、OCR結果、修正内容、確定内容はこの端末のIndexedDBにのみ保存されます。</p><h2>対応ファイル</h2><p>JPEG、PNG、HEIC（ブラウザ対応時）、PDFの1ページ目。最大25MB。</p><button className="danger" onClick={async()=>{if(confirm('この端末の履歴をすべて削除しますか？')){await db.history.clear();alert('履歴を削除しました')}}}>すべての履歴を削除</button></div></section>}</main><footer>Schedule Scan · 端末内OCR</footer></>
}
function Field({type,value,candidates,selected,onChange,onSelect}:{type:FieldType;value:string;candidates:Candidate[];selected?:string;onChange:(v:string)=>void;onSelect:(c:Candidate)=>void}){return<fieldset><legend>{labels[type]}{type==='endTime'&&<small>（空欄可）</small>}</legend><input type={type==='date'?'date':type.includes('Time')?'time':'text'} value={value} onChange={e=>onChange(e.target.value)}/>{candidates.length>0&&<div className="candidates">{candidates.map(c=><button type="button" key={c.id} className={selected===c.id?'chosen':''} onClick={()=>onSelect(c)} style={{'--field-color':colors[type]}as React.CSSProperties}><span>{c.value}</span><b>{c.confidence}%</b><small>{c.reason}</small></button>)}</div>}</fieldset>}
function SimpleForm({draft,setDraft}:{draft:EventDraft;setDraft:(d:EventDraft)=>void}){return<>{(['title','date','startTime','endTime','location']as FieldType[]).map(k=><label key={k}>{labels[k]}{k==='endTime'&&'（任意）'}<input type={k==='date'?'date':k.includes('Time')?'time':'text'} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>住所（任意）<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>メモ（任意）<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></>}
