import type{Candidate,CandidateMap,EventDraft,FieldType,OcrWord}from'./types'
const empty=():CandidateMap=>({title:[],date:[],startTime:[],endTime:[],location:[]})
const unique=(a:Candidate[])=>a.filter((v,i,x)=>x.findIndex(y=>y.value===v.value)===i).sort((a,b)=>b.confidence-a.confidence).slice(0,3)
const cand=(type:FieldType,value:string,confidence:number,words:OcrWord[],reason:string):Candidate=>({id:`${type}-${words[0]?.id??value}`,value,confidence:Math.max(1,Math.min(99,Math.round(confidence))),wordIds:words.map(w=>w.id),reason})
const compact=(s:string)=>s.replace(/\s+/g,'')
const dateValue=(s:string)=>{s=compact(s);const e=s.match(/令和(\d+)年(\d+)月(\d+)日/);if(e)return`${2018+Number(e[1])}-${e[2].padStart(2,'0')}-${e[3].padStart(2,'0')}`;const f=s.match(/(20\d{2})[年\/\-.](\d{1,2})[月\/\-.](\d{1,2})日?/);if(f)return`${f[1]}-${f[2].padStart(2,'0')}-${f[3].padStart(2,'0')}`;const m=s.match(/(\d{1,2})月(\d{1,2})日/);return m?`${new Date().getFullYear()}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`:''}
const timeValue=(s:string)=>{s=compact(s);const m=s.match(/(?:午[前後])?(\d{1,2})(?::|時)(\d{1,2})?(?:分)?/);if(!m)return'';let h=Number(m[1]);if(s.includes('午後')&&h<12)h+=12;return`${String(h).padStart(2,'0')}:${String(Number(m[2]||0)).padStart(2,'0')}`}
export function extractCandidates(words:OcrWord[],height:number):CandidateMap{const out=empty(),lines=new Map<string,OcrWord[]>();for(const w of words.filter(x=>x.text.trim()))lines.set(w.lineId,[...(lines.get(w.lineId)||[]),w]);const rows=[...lines.values()].map(ws=>ws.sort((a,b)=>a.box.x-b.box.x)).map(ws=>({words:ws,text:ws.map(w=>w.text).join(' '),y:Math.min(...ws.map(w=>w.box.y)),size:Math.max(...ws.map(w=>w.fontSize)),conf:ws.reduce((n,w)=>n+w.confidence,0)/ws.length}));for(const r of rows){const dense=compact(r.text),d=dateValue(dense);if(d)out.date.push(cand('date',d,r.conf+5,r.words,'日付の表記に一致'));const times=[...dense.matchAll(/(?:午[前後])?\d{1,2}(?::|時)\d{0,2}(?:分)?/g)];times.forEach((mt,index)=>{const v=timeValue(mt[0]),explicitEnd=/終了|終演|閉会/.test(dense),rangeEnd=index===1&&times.length>1&&/[~〜～\-–—へ]/.test(dense.slice((times[0].index||0)+times[0][0].length,mt.index)),type=explicitEnd||rangeEnd?'endTime':'startTime';out[type].push(cand(type,v,r.conf+(/開始|開演|受付|日時/.test(dense)?5:0),r.words,type==='endTime'?'終了時刻または時間範囲':'時刻表記と開始を示す周辺語'))});if(/会場|場所/.test(dense)){const v=dense.replace(/^.*?(?:会場|場所)[:：]?/,'').trim();if(v)out.location.push(cand('location',v,r.conf+5,r.words,'会場を示す見出し'))}else if(/会館|ホール|センター|ホテル|劇場|体育館|スタジアム/.test(dense))out.location.push(cand('location',dense,r.conf,r.words,'施設名を示す語'))}const titles=rows.filter(r=>{const d=compact(r.text);return d.length>=5&&d.length<=80&&!dateValue(d)&&!timeValue(d)&&!/会場|場所|〒|https?:|謹啓|拝啓|問い合わせ|TEL|FAX/.test(d)}).map(r=>{const text=compact(r.text),heading=/説明会.*(?:ご案内|案内)$/.test(text),keyword=/説明会|講演会|コンサート|大会|イベント/.test(text),sentence=/[。、]|申し|ください|について/.test(text),score=r.conf+(r.y<height*.4?10:0)+Math.min(18,r.size/2)+(heading?35:keyword?12:0)-(text.length>45?18:0)-(sentence?15:0);return{...r,text,heading,score}}).sort((a,b)=>b.score-a.score).slice(0,3);out.title=titles.map(r=>cand('title',r.text,r.score,r.words,r.heading?'説明会名を示す短い見出し':'画像上部の大きな見出し'));(Object.keys(out)as FieldType[]).forEach(k=>out[k]=unique(out[k]));return out}
export const initialDraft=(c:CandidateMap):EventDraft=>({title:c.title[0]?.value||'',date:c.date[0]?.value||'',startTime:c.startTime[0]?.value||'',endTime:c.endTime[0]?.value||'',location:c.location[0]?.value||'',address:'',notes:''})
