import type{Candidate,CandidateMap,EventDraft,FieldType,OcrWord}from'./types'
const empty=():CandidateMap=>({title:[],date:[],startTime:[],endTime:[],location:[]})
const unique=(a:Candidate[])=>a.filter((v,i,x)=>x.findIndex(y=>y.value===v.value)===i).sort((a,b)=>b.confidence-a.confidence).slice(0,3)
const cand=(type:FieldType,value:string,confidence:number,words:OcrWord[],reason:string):Candidate=>({id:`${type}-${words[0]?.id??value}`,value,confidence:Math.max(1,Math.min(99,Math.round(confidence))),wordIds:words.map(w=>w.id),reason})
const compact=(s:string)=>s.replace(/\s+/g,'')
const dateValue=(s:string)=>{s=compact(s);const e=s.match(/令和(\d+)年(\d+)月(\d+)日/);if(e)return`${2018+Number(e[1])}-${e[2].padStart(2,'0')}-${e[3].padStart(2,'0')}`;const f=s.match(/(20\d{2})[年\/\-.](\d{1,2})[月\/\-.](\d{1,2})日?/);if(f)return`${f[1]}-${f[2].padStart(2,'0')}-${f[3].padStart(2,'0')}`;const m=s.match(/(\d{1,2})月(\d{1,2})日/);return m?`${new Date().getFullYear()}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`:''}
const timeValue=(s:string)=>{s=compact(s);const m=s.match(/(?:午[前後])?(\d{1,2})(?::|時)(\d{1,2})?(?:分)?/);if(!m)return'';let h=Number(m[1]);if(s.includes('午後')&&h<12)h+=12;return`${String(h).padStart(2,'0')}:${String(Number(m[2]||0)).padStart(2,'0')}`}
export function extractCandidates(words:OcrWord[],height:number):CandidateMap{const out=empty(),lines=new Map<number,OcrWord[]>();for(const w of words.filter(x=>x.text.trim())){const k=Math.round(w.box.y/Math.max(16,w.fontSize*.8));lines.set(k,[...(lines.get(k)||[]),w])}const rows=[...lines.values()].map(ws=>ws.sort((a,b)=>a.box.x-b.box.x)).map(ws=>({words:ws,text:ws.map(w=>w.text).join(' '),y:Math.min(...ws.map(w=>w.box.y)),size:Math.max(...ws.map(w=>w.fontSize)),conf:ws.reduce((n,w)=>n+w.confidence,0)/ws.length}));for(const r of rows){const dense=compact(r.text),d=dateValue(dense);if(d)out.date.push(cand('date',d,r.conf+8,r.words,'日付の表記に一致'));const times=[...dense.matchAll(/(?:午[前後])?\d{1,2}(?::|時)\d{0,2}(?:分)?/g)];times.forEach((mt,index)=>{const v=timeValue(mt[0]),explicitEnd=/終了|終演|閉会/.test(dense),rangeEnd=index===1&&times.length>1&&/[~〜～\-–—へ]/.test(dense.slice((times[0].index||0)+times[0][0].length,mt.index)),type=explicitEnd||rangeEnd?'endTime':'startTime';out[type].push(cand(type,v,r.conf+(/開始|開演|受付/.test(dense)?9:0),r.words,type==='endTime'?'終了時刻または時間範囲':'時刻表記と開始を示す周辺語'))});if(/会場|場所|会館|ホール|センター|ホテル|劇場|体育館|スタジアム|ビル/.test(dense)){const v=dense.replace(/^.*?(?:会場|場所)[:：]?/,'').trim();if(v)out.location.push(cand('location',v,r.conf+6,r.words,'会場・施設を示す語'))}}const titles=rows.filter(r=>r.text.length>=3&&!dateValue(r.text)&&!timeValue(r.text)&&!/会\s*場|場\s*所|〒|https?:/.test(r.text)).map(r=>({...r,score:r.conf+(r.y<height*.35?10:0)+Math.min(15,r.size/2)})).sort((a,b)=>b.score-a.score).slice(0,3);out.title=titles.map(r=>cand('title',compact(r.text),r.score,r.words,r.y<height*.35?'画像上部の大きな見出し':'大きな見出し'));(Object.keys(out)as FieldType[]).forEach(k=>out[k]=unique(out[k]));return out}
export const initialDraft=(c:CandidateMap):EventDraft=>({title:c.title[0]?.value||'',date:c.date[0]?.value||'',startTime:c.startTime[0]?.value||'',endTime:c.endTime[0]?.value||'',location:c.location[0]?.value||'',address:'',notes:''})
